lang: C
dist: trusty
sudo: required
script:
- sudo apt-get install -y rpm cpio rpm2cpio bsdtar
- ./build_sledgehammer.sh
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
deploy:
  provider: s3
  access_key_id: AKIAJF4QJY2A23DY6YTQ
  secret_access_key:
    secure: gP7UXicC164biy1WYb8JyHwV/PjEa3Rko5mmF/3t6mEP6cfsHO+Ywbkr4WuHzIVb5U8luazYuWTRHMRBzec1vyfAiw8gpQvlzTxpzi9C2Q5s2qSDnfxFixrhwzcU8AsPH75PyXq0LfzQ9KW5N9aIBSmE22H/baMuVvmnaCQX05/ukH7tMig8yHO91DbPoMfR/iMb1xBGIqMkfEBPqs4h1k5Rwl4+bodeE9qMpH72cSqH7YCEg15bC4dhj3/TebxNUwJOFhGeiOL0jjIGxiRQDyejF9ueI2Z9pY266yVAKMp4BgnOE+Qh726eRdfIqNB9pJJyJTPIMZ5TpXi8+w42DxfuhGE1/0ZhXnI9/uCsp1QVtpV07fXcb3wgm9GNQQm/xnIZh1bIkU64C33zgua5vHDQ6ieqJSOfTekTX12xO34CCavW2K1vE0NTz4FzumQCoYDE2f0ZrI12sLA2ifGccncpAckg8D6/lgDKakiM/Sstz95/iTHwD1zYuBp0UhViLe61KSdmNUtmIYKgfUfd+wCSomBlosoFoJtBedNCjO7zy3T2LUPwLw4QalorCkNve0KTP4X4GvU1vTyDlqV4dRik3L5fM8GsA9tQ24BVnOX+j2nbnckep6F3ZhLCCr8u+3QX/wjhraT13VmR7OnU/48FFLTwryOCGBCiToP9N7M=
  bucket: rackn-sledgehammer
  region: us-west-2
  local-dir: rackn-sledgehammer
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/sledgehammer
    tags: true
